### ISSUE TITLE
Register-Passkey Error

### ISSUE THREAD

**Issue by tikesavage** [MichaelGrafnetter/webauthn-interop#13]
Invoke-MgGraphRequest: GET https://graph.microsoft.com/beta/users/<UPNHERE>/authentication/fido2Methods/creationOptions?challengeTimeoutInMinutes=5 HTTP/2.0 405 Method Not Allowed Vary: Accept-Encoding Strict-Transport-Security: max-age=31536000 request-id: 1686c46f-9635-41e3-b911-43748b60bd98
client-request-id: 3bc06849-4266-4b48-9a73-b1e8bfd5e7a8 x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"008","RoleInstance":"BL02EPF0001B4CE"}} Link:
<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:copilotExportAPI&from=2024-07-01&to=2024-08-01>;rel="deprecation";type="text/html" deprecation: Tue, 02 Jul 2024 23:59:59 GMT sunset: Thu, 02 Jul 2026 23:59:59 GMT Date: Mon, 12 Aug 2024 15:39:14  
GMT Content-Type: application/json Content-Encoding: gzip  {"error":{"code":"methodNotAllowed","message":"The method is not supported for this URL.","innerError":{"message":"The method is not supported for this
URL.","date":"2024-08-12T15:39:14","request-id":"1686c46f-9635-41e3-b911-43748b60bd98","client-request-id":"3bc06849-4266-4b48-9a73-b1e8bfd5e7a8"}}}

*i pulled my UPN out of the error.

**Comment by MichaelGrafnetter** [comment]
The operation is not supported for SELF, maybe that is the reason of the error.
