### ISSUE TITLE
readme reference to AuthenticatorGetAssertion

### ISSUE THREAD

**Issue by pionl** [MichaelGrafnetter/webauthn-interop#19]
Hi, in the readme you are referencing to docs that were deleted by this [commit](https://github.com/MichaelGrafnetter/webauthn-interop/commit/ee6af6af7a4c6d4a64b6ee10526b345b1199265b#diff-2056afebdc86a59a8a8d2422cf004f9da510d73b88437ae6e284f6fb245da772). A mistake? thank you

--- 

Credential registration is performed by calling the [AuthenticatorMakeCredential](https://github.com/MichaelGrafnetter/webauthn-interop/blob/main/Documentation/API/DSInternals.Win32.WebAuthn/WebAuthnApi/AuthenticatorMakeCredential.md) or [AuthenticatorMakeCredentialAsync](https://github.com/MichaelGrafnetter/webauthn-interop/blob/main/Documentation/API/DSInternals.Win32.WebAuthn/WebAuthnApi/AuthenticatorMakeCredentialAsync.md) method:

**Comment by MichaelGrafnetter** [comment]
Hi @pionl , the readme needs to be updated, thanks for pointing it out. For now, please see how the UI is doing the call in [MainWindowViewModel.cs](https://github.com/MichaelGrafnetter/webauthn-interop/blob/main/Src/Fido2UI/Views/MainWindow/MainWindowViewModel.cs#L97).

**Comment by pionl** [comment]
Thank you!
